name = "Peripheral"
license = "MIT"
licenselink = "https://github.com/myquay/hugo-theme-peripheral/blob/main/LICENSE"
description = "A fast, clean, Hugo theme with minimal dependencies"
homepage = "https://github.com/myquay/hugo-theme-peripheral"
demosite = "https://myquay.github.io/hugo-theme-peripheral-example"
tags = ["blog"]
features = ["blog"]
min_version = "0.111.3"

[author]
  name = "Michael McKenna"
  homepage = "https://michael-mckenna.com"
